"""
Pydantic models for SQL Query Generation Environment.

Defines Action (SQL query submission), Observation (question + feedback),
and State (environment state) for type safety and validation.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class SQLAction(BaseModel):
    """Action submitted by agent: a SQL query to execute."""

    query: str = Field(
        ...,
        description="The SQL query generated by the agent"
    )
    reasoning: str = Field(
        default="",
        description="Optional explanation of the query strategy"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Optional metadata (e.g., query plan notes)"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "query": "SELECT c.name, COUNT(o.id) as order_count FROM customers c LEFT JOIN orders o ON c.id = o.customer_id WHERE c.city = 'New York' GROUP BY c.id, c.name ORDER BY order_count DESC",
                "reasoning": "Join customers with orders, filter by city, count orders per customer",
                "metadata": {}
            }
        }


class SQLObservation(BaseModel):
    """Observation returned by reset() and step()."""

    question: str = Field(
        ...,
        description="Natural language question asking for data"
    )
    database_schema: str = Field(
        ...,
        description="Description of relevant database tables and columns"
    )
    sample_data: Optional[str] = Field(
        default=None,
        description="Optional sample of relevant data to show structure"
    )
    expected_columns: List[str] = Field(
        default_factory=list,
        description="Expected output columns"
    )
    expected_row_count_approx: Optional[int] = Field(
        default=None,
        description="Approximate number of rows expected"
    )
    
    # Only populated after step()
    query_feedback: Optional[str] = Field(
        default=None,
        description="Feedback on the submitted query (after step)"
    )
    execution_result: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Result of query execution (after step)"
    )
    actual_columns: Optional[List[str]] = Field(
        default=None,
        description="Columns returned by the query (after step)"
    )
    actual_row_count: Optional[int] = Field(
        default=None,
        description="Number of rows returned (after step)"
    )


class RewardBreakdown(BaseModel):
    """Detailed reward component breakdown."""

    correctness: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Correctness score (query runs, returns right results)"
    )
    efficiency: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Efficiency score (good query plan, uses indexes)"
    )
    safety: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Safety score (SQL injection protection, null handling)"
    )
    penalty: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Penalty for violations (unnecessary complexity, etc)"
    )


class Reward(BaseModel):
    """Reward returned by step()."""

    score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Overall reward score"
    )
    breakdown: RewardBreakdown = Field(
        ...,
        description="Detailed component scores"
    )
    feedback: str = Field(
        ...,
        description="Human-readable explanation of the reward"
    )


class SQLState(BaseModel):
    """Environment state (for state() method)."""

    question_id: str = Field(..., description="Current question identifier")
    question: str = Field(..., description="Current question text")
    submitted_query: Optional[str] = Field(default=None, description="Last submitted query")
    last_reward: Optional[float] = Field(default=None, description="Reward from last step")
    is_done: bool = Field(default=False, description="Whether episode is complete")
    step_count: int = Field(default=0, description="Number of steps taken")
    cumulative_reward: float = Field(default=0.0, description="Total reward accumulated")


class StepResult(BaseModel):
    """Result returned by step()."""

    observation: SQLObservation
    reward: Reward
    done: bool
    info: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata"
    )
